/*
 * app/web/web_page.c — the embedded HTML config page, served by web.c
 * at GET /.
 *
 * Single-file page: inline CSS, vanilla JS using fetch() against
 * /api/config / /api/save / /api/reboot. No framework, no images, no
 * external assets — fits in a few KB of flash.
 *
 * Stored as `const char[]` in .rodata so it lives in the same flash
 * region as the rest of .text. The size is captured at compile time
 * via sizeof so web.c can pass it as Content-Length without a runtime
 * strlen.
 */

#include <stddef.h>

const char WEB_INDEX_HTML[] =
    "<!doctype html>\n"
    "<html lang=\"en\">\n"
    "<head>\n"
    "<meta charset=\"utf-8\">\n"
    "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
    "<title>CMC Configuration</title>\n"
    "<style>\n"
    "  :root{--fg:#222;--bg:#f7f7f7;--card:#fff;--accent:#2c6fbb;--ok:#1b7a3d;--warn:#a45a00;--err:#a33;--mute:#666;}\n"
    "  body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;background:var(--bg);color:var(--fg);margin:0;padding:16px;}\n"
    "  h1{margin:0 0 16px;font-size:20px}\n"
    "  section{background:var(--card);border:1px solid #ddd;border-radius:6px;padding:12px 14px;margin-bottom:12px;max-width:640px}\n"
    "  h2{margin:0 0 8px;font-size:14px;color:var(--accent);text-transform:uppercase;letter-spacing:.05em}\n"
    "  .hint{font-size:12px;color:var(--mute);margin:0 0 8px}\n"
    "  table{width:100%;border-collapse:collapse}\n"
    "  td{padding:4px 8px 4px 0;vertical-align:middle}\n"
    "  td.k{width:200px;font-size:13px}\n"
    "  td.u{width:60px;font-size:12px;color:var(--mute)}\n"
    "  input[type=text],input[type=number]{width:140px;padding:4px 6px;border:1px solid #bbb;border-radius:4px;font-family:monospace;font-size:13px}\n"
    "  button{padding:6px 12px;border:1px solid #999;background:#eee;border-radius:4px;cursor:pointer;font-size:13px;margin-right:6px}\n"
    "  button.primary{background:var(--accent);color:#fff;border-color:var(--accent)}\n"
    "  button.warn{background:var(--warn);color:#fff;border-color:var(--warn)}\n"
    "  .status{font-family:monospace;font-size:13px;line-height:1.6;color:#333}\n"
    "  .status b{color:var(--accent)}\n"
    "  .live{display:inline-block;padding:2px 8px;background:#eef5ff;border-radius:3px;font-family:monospace;font-size:12px;color:#333}\n"
    "  #toast{position:fixed;bottom:16px;right:16px;background:var(--ok);color:#fff;padding:8px 14px;border-radius:4px;opacity:0;transition:opacity .25s;font-size:13px}\n"
    "  #toast.show{opacity:1}\n"
    "  #toast.err{background:var(--err)}\n"
    "</style>\n"
    "</head>\n"
    "<body>\n"
    "<h1>CMC Configuration</h1>\n"

    "<section>\n"
    " <h2>Active protocol</h2>\n"
    " <p class=\"hint\">Which network protocol runs on this CMC. Applied at boot only \xe2\x80\x94 change here stages the value; the CMC starts using it after <b>Save + Reboot</b>.</p>\n"
    " <div style=\"display:flex;align-items:center;gap:10px;margin:8px 0\">\n"
    "  <select id=\"proto\">\n"
    "   <option value=\"0\">CAMERAD</option>\n"
    "   <option value=\"1\">VISCA (stub \xe2\x80\x94 not implemented yet)</option>\n"
    "  </select>\n"
    "  <button onclick=\"applyProto()\">Stage</button>\n"
    "  <span id=\"proto_current\" style=\"color:#666;font-size:12px\"></span>\n"
    " </div>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Status</h2>\n"
    " <div class=\"status\">\n"
    "  MAC: <b id=\"st_mac\">-</b><br>\n"
    "  Uptime: <b id=\"st_up\">-</b><br>\n"
    " </div>\n"
    " <button onclick=\"loadConfig()\">Refresh</button>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Network</h2>\n"
    " <p class=\"hint\">Changes take effect after a reboot. Use <b>Save + Reboot</b> below.</p>\n"
    " <table>\n"
    "  <tr><td class=\"k\">IP address</td><td><input id=\"net_ip\" type=\"text\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">Netmask</td><td><input id=\"net_mask\" type=\"text\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">Gateway</td><td><input id=\"net_gw\" type=\"text\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">CMC device #</td><td><input id=\"net_dev\" type=\"number\" min=\"1\" max=\"255\"></td><td class=\"u\">1..255 (advertised as return_device_no)</td></tr>\n"
    "  <tr><td colspan=\"3\" style=\"padding-top:8px;font-weight:bold\">Panel A (strict — leave IP blank to disable)</td></tr>\n"
    "  <tr><td class=\"k\">Panel A IP</td><td><input id=\"net_pa_ip\" type=\"text\" placeholder=\"e.g. 192.1.0.50\"></td><td class=\"u\">expected source of A's POLLs</td></tr>\n"
    "  <tr><td class=\"k\">Panel A port</td><td><input id=\"net_tcp\" type=\"number\" min=\"1024\" max=\"65535\"></td><td class=\"u\">advertised to A as return_port (default 30001)</td></tr>\n"
    "  <tr><td colspan=\"3\" style=\"padding-top:8px;font-weight:bold\">Panel B (leave IP blank to disable)</td></tr>\n"
    "  <tr><td class=\"k\">Panel B IP</td><td><input id=\"net_pb_ip\" type=\"text\" placeholder=\"e.g. 192.1.0.51\"></td><td class=\"u\">expected source of B's POLLs</td></tr>\n"
    "  <tr><td class=\"k\">Panel B port</td><td><input id=\"net_pb_port\" type=\"number\" min=\"1024\" max=\"65535\"></td><td class=\"u\">advertised to B as return_port (default 30004; different from A so the W6100 can host both listens)</td></tr>\n"
    " </table>\n"
    " <button onclick=\"applyNet()\">Stage network</button>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Motion limits</h2>\n"
    " <p class=\"hint\">Applied live on apply. Save to flash to persist.</p>\n"
    " <table>\n"
    "  <tr><td class=\"k\">Velocity limit</td><td><input id=\"lim_vel\" type=\"number\" step=\"any\"></td><td class=\"u\">rad/s</td></tr>\n"
    "  <tr><td class=\"k\">Position limit (lo)</td><td><input id=\"lim_plo\" type=\"number\" step=\"any\"> <button type=\"button\" onclick=\"capturePos('lim_plo')\" title=\"Capture the current position into this field\">Capture</button></td><td class=\"u\">rad</td></tr>\n"
    "  <tr><td class=\"k\">Position limit (hi)</td><td><input id=\"lim_phi\" type=\"number\" step=\"any\"> <button type=\"button\" onclick=\"capturePos('lim_phi')\" title=\"Capture the current position into this field\">Capture</button></td><td class=\"u\">rad</td></tr>\n"
    "  <tr><td class=\"k\">Current position (live)</td><td><span class=\"live\" id=\"pos_cur\">-</span></td><td class=\"u\">rad</td></tr>\n"
    "  <tr><td class=\"k\">Acceleration limit</td><td><input id=\"lim_acc\" type=\"number\" step=\"any\"></td><td class=\"u\">rad/s\xc2\xb2</td></tr>\n"
    " </table>\n"
    " <button onclick=\"applyLimits()\">Apply limits</button>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Joystick calibration</h2>\n"
    " <p class=\"hint\">Tune to your panel's stick range. Defaults match a CAMERAD panel (\xc2\xb1127).</p>\n"
    " <table>\n"
    "  <tr><td class=\"k\">Raw center</td><td><input id=\"js_c\" type=\"number\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">Raw full +</td><td><input id=\"js_fp\" type=\"number\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">Raw full \xe2\x88\x92</td><td><input id=\"js_fn\" type=\"number\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">Deadband</td><td><input id=\"js_db\" type=\"number\" min=\"0\"></td><td class=\"u\"></td></tr>\n"
    "  <tr><td class=\"k\">Current raw (live)</td><td><span class=\"live\" id=\"js_cur\">-</span></td><td class=\"u\"></td></tr>\n"
    "  <tr><td colspan=\"3\" style=\"padding-top:8px;font-weight:bold\">Joystick feel (motor 0x2300:6/7/8 — saved in motor flash on Save)</td></tr>\n"
    "  <tr><td class=\"k\">Accel up</td><td><input id=\"js_aup\" type=\"number\" step=\"any\" min=\"0\"></td><td class=\"u\">rad/s² (cap on speed-up; 0 = off)</td></tr>\n"
    "  <tr><td class=\"k\">Accel down</td><td><input id=\"js_adn\" type=\"number\" step=\"any\" min=\"0\"></td><td class=\"u\">rad/s² (cap on slow-down; 0 = off)</td></tr>\n"
    "  <tr><td class=\"k\">Accel jerk</td><td><input id=\"js_ajk\" type=\"number\" step=\"any\" min=\"0\"></td><td class=\"u\">rad/s³ (smooth start; 0 = step to cap)</td></tr>\n"
    " </table>\n"
    " <button onclick=\"applyJoy()\">Apply joystick</button>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Dynamics</h2>\n"
    " <p class=\"hint\">Load factor scales the motor's velocity-loop kp / ki. Drag to match the payload; the value is sent to the motor (OD 0x2300:5) on release.</p>\n"
    " <div style=\"display:flex;align-items:center;gap:10px;margin:8px 0\">\n"
    "  <span style=\"font-size:12px;color:#666;min-width:80px;text-align:right\">Light load</span>\n"
    "  <input id=\"dyn_lf\" type=\"range\" min=\"0.3\" max=\"2.0\" step=\"0.05\" value=\"1.0\" style=\"flex:1\">\n"
    "  <span style=\"font-size:12px;color:#666;min-width:80px\">Heavy load</span>\n"
    " </div>\n"
    " <div style=\"text-align:center;font-family:monospace;font-size:14px\">\n"
    "  current: <span id=\"dyn_lf_val\">1.00</span>\n"
    " </div>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Axis role</h2>\n"
    " <p class=\"hint\">Which CAMERAD MOVEMENT field this controller consumes. Every frame carries all 8 axis values; the CMC uses the one selected here. Applied live on Apply; persisted on Save all to flash.</p>\n"
    " <div style=\"display:flex;align-items:center;gap:10px;margin:8px 0\">\n"
    "  <select id=\"axis_role\">\n"
    "   <option value=\"1\">Pan</option>\n"
    "   <option value=\"2\">Tilt</option>\n"
    "   <option value=\"4\">Zoom</option>\n"
    "   <option value=\"8\">Focus</option>\n"
    "   <option value=\"16\">X</option>\n"
    "   <option value=\"32\">Y</option>\n"
    "   <option value=\"64\">Height</option>\n"
    "   <option value=\"128\">Fader</option>\n"
    "  </select>\n"
    "  <button onclick=\"applyAxisRole()\">Apply</button>\n"
    " </div>\n"
    "</section>\n"

    "<section id=\"home_sec\" style=\"display:none\">\n"
    " <h2>Homing</h2>\n"
    " <p class=\"hint\">Incremental encoder detected. Drives at the configured home_velocity until the armature current exceeds home_current (stall), then zeros the encoder at that position. The rotor <b>will</b> move — clear any objects from the rotation path.</p>\n"
    " <div style=\"display:flex;align-items:center;gap:10px;margin:8px 0\">\n"
    "  <button class=\"primary\" onclick=\"homeAxis()\" id=\"home_btn\">Home to end stop</button>\n"
    "  <span>Status: <b id=\"home_st\">-</b></span>\n"
    "  <span>Homed: <b id=\"home_flag\">-</b></span>\n"
    " </div>\n"
    "</section>\n"

    "<section>\n"
    " <h2>Persist</h2>\n"
    " <button class=\"primary\" onclick=\"saveAll()\">Save all to flash</button>\n"
    " <button class=\"warn\" onclick=\"saveAndReboot()\">Save + Reboot</button>\n"
    "</section>\n"

    "<div id=\"toast\"></div>\n"

    "<script>\n"
    "let cfg = null;\n"
    "function $(id){return document.getElementById(id);}\n"
    "function toast(msg, err){const t=$('toast');t.textContent=msg;t.className='show'+(err?' err':'');setTimeout(()=>t.className='',1800);}\n"
    "async function loadConfig(){\n"
    "  try{\n"
    "    const r = await fetch('/api/config'); cfg = await r.json();\n"
    "    $('st_mac').textContent = cfg.status.mac;\n"
    "    $('st_up').textContent  = cfg.status.uptime_pretty;\n"
    "    $('net_ip').value   = cfg.net.ip;\n"
    "    $('net_mask').value = cfg.net.netmask;\n"
    "    $('net_gw').value   = cfg.net.gateway;\n"
    "    $('net_dev').value     = cfg.net.cmc_device_no;\n"
    "    $('net_tcp').value     = cfg.net.tcp_camerad_port;\n"
    "    // 0.0.0.0 means 'slot disabled' in strict mode — show blank instead\n"
    "    // so the operator sees the field as 'empty / unset' and knows to fill it.\n"
    "    $('net_pa_ip').value   = (cfg.net.panel_a_ip === '0.0.0.0') ? '' : cfg.net.panel_a_ip;\n"
    "    $('net_pb_ip').value   = (cfg.net.panel_b_ip === '0.0.0.0') ? '' : cfg.net.panel_b_ip;\n"
    "    $('net_pb_port').value = cfg.net.panel_b_port;\n"
    "    // active_protocol dropdown. Also show 'currently running' vs 'staged' so\n"
    "    // the operator knows a reboot is needed. There's no separate 'running'\n"
    "    // field in the JSON (main_loop snapshots at boot); we show the staged\n"
    "    // value and note that the CMC boots with whatever was last saved.\n"
    "    const proto = (typeof cfg.net.active_protocol === 'number') ? cfg.net.active_protocol : 0;\n"
    "    $('proto').value = String(proto);\n"
    "    $('proto_current').textContent = 'staged: ' + (proto === 1 ? 'VISCA' : 'CAMERAD') + ' (reboot to apply)';\n"
    "    // null = unset / no-limit (we emit null for +/-Inf on the CMC side).\n"
    "    // Leave the field blank in that case so the operator sees 'unset', not '0'.\n"
    "    const setNum = (id, v) => { $(id).value = (v === null || v === undefined) ? '' : v; };\n"
    "    setNum('lim_vel', cfg.limits.velocity);\n"
    "    setNum('lim_plo', cfg.limits.position_lo);\n"
    "    setNum('lim_phi', cfg.limits.position_hi);\n"
    "    setNum('lim_acc', cfg.limits.accel);\n"
    "    const pc = cfg.limits.position_current;\n"
    "    $('pos_cur').textContent = (pc == null) ? '-' : Number(pc).toFixed(4);\n"
    "    $('js_c').value     = cfg.joystick.raw_center;\n"
    "    $('js_fp').value    = cfg.joystick.raw_full_pos;\n"
    "    $('js_fn').value    = cfg.joystick.raw_full_neg;\n"
    "    $('js_db').value    = cfg.joystick.raw_deadband;\n"
    "    $('js_cur').textContent = cfg.joystick.raw_current;\n"
    "    $('js_aup').value   = cfg.joystick.vel_accel_up;\n"
    "    $('js_adn').value   = cfg.joystick.vel_accel_dn;\n"
    "    $('js_ajk').value   = cfg.joystick.vel_accel_jerk;\n"
    "    // dynamics.load_factor mirrors motor 0x2300:5. Default 1.0 on cold boot;\n"
    "    // motor's actual saved value is authoritative (we'd need an SDO read to fetch it).\n"
    "    const lf = (cfg.dynamics.load_factor != null) ? cfg.dynamics.load_factor : 1.0;\n"
    "    $('dyn_lf').value = lf;\n"
    "    $('dyn_lf_val').textContent = (+lf).toFixed(2);\n"
    "    // Homing section — visible only for incremental encoders (axis.encoder_incremental=1,\n"
    "    // latched by the CMC once it has seen NOT_HOMED in motor fault_flags at least once).\n"
    "    updateHoming(cfg.axis);\n"
    "    if (cfg.axis && cfg.axis.role) { $('axis_role').value = String(cfg.axis.role); }\n"
    "  }catch(e){toast('load failed: '+e, true);}\n"
    "}\n"
    "async function applyAxisRole(){\n"
    "  try{await post('/api/config',{axis:{role:+$('axis_role').value}}); toast('axis role applied');}\n"
    "  catch(e){toast('apply failed: '+e,true);}\n"
    "}\n"
    "const HOME_ST = ['idle','running','done','failed'];\n"
    "function updateHoming(a){\n"
    "  if (!a) return;\n"
    "  $('home_sec').style.display = a.encoder_incremental ? '' : 'none';\n"
    "  $('home_flag').textContent  = a.is_homed ? 'yes' : 'no';\n"
    "  const s = a.home_status|0;\n"
    "  $('home_st').textContent   = HOME_ST[s] || ('?' + s);\n"
    "  // Disable the button while a home is in progress so double-clicks don't\n"
    "  // pile up requests (the CMC would reject them but the UX is nicer).\n"
    "  $('home_btn').disabled = (s === 1);\n"
    "}\n"
    "async function homeAxis(){\n"
    "  try{await post('/api/home'); toast('home started');}\n"
    "  catch(e){toast('home failed: '+e,true);}\n"
    "}\n"
    "async function post(path, body){\n"
    "  const r = await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:body?JSON.stringify(body):''});\n"
    "  if(!r.ok){throw new Error('http '+r.status);}\n"
    "  return r.text();\n"
    "}\n"
    "async function applyNet(){\n"
    "  // Blank IP field -> send 0.0.0.0 explicitly (strict mode = disable slot).\n"
    "  const ipOrZero = v => (v && v.trim().length) ? v.trim() : '0.0.0.0';\n"
    "  try{await post('/api/config',{net:{\n"
    "      ip:$('net_ip').value,netmask:$('net_mask').value,gateway:$('net_gw').value,\n"
    "      cmc_device_no:+$('net_dev').value,\n"
    "      tcp_camerad_port:+$('net_tcp').value,\n"
    "      panel_a_ip:ipOrZero($('net_pa_ip').value),\n"
    "      panel_b_ip:ipOrZero($('net_pb_ip').value),\n"
    "      panel_b_port:+$('net_pb_port').value\n"
    "    }});\n"
    "    toast('network staged (reboot to apply)');loadConfig();\n"
    "  }catch(e){toast('apply failed: '+e,true);}\n"
    "}\n"
    "async function applyProto(){\n"
    "  const v = +$('proto').value;\n"
    "  try{await post('/api/config',{net:{active_protocol:v}});\n"
    "    toast('protocol staged (Save + Reboot to apply)');loadConfig();\n"
    "  }catch(e){toast('apply failed: '+e,true);}\n"
    "}\n"
    "async function applyLimits(){\n"
    "  // Skip empty fields so blank position-limit (= unset / no-limit on CMC) doesn't\n"
    "  // round-trip as NaN. Only send keys with a real numeric value.\n"
    "  const lim = {}; const pick = (key, id) => { const v = $(id).value; if (v !== '' && v !== null) lim[key] = +v; };\n"
    "  pick('velocity','lim_vel'); pick('position_lo','lim_plo'); pick('position_hi','lim_phi'); pick('accel','lim_acc');\n"
    "  try{await post('/api/config',{limits:lim});toast('limits applied');loadConfig();}\n"
    "  catch(e){toast('apply failed: '+e,true);}\n"
    "}\n"
    "async function capturePos(id){\n"
    "  // Snapshot the live position into the target lo/hi field. Rounds to 4 dp so\n"
    "  // the input doesn't fill up with float noise (limits are stored as f32 anyway).\n"
    "  try{\n"
    "    const r = await fetch('/api/config'); const c = await r.json();\n"
    "    const v = c.limits.position_current;\n"
    "    if (v === null || v === undefined){ toast('no live position',true); return; }\n"
    "    $(id).value = Number(v).toFixed(4);\n"
    "    toast('captured '+$(id).value+' rad');\n"
    "  }catch(e){toast('capture failed: '+e,true);}\n"
    "}\n"
    "async function applyJoy(){\n"
    "  try{await post('/api/config',{joystick:{raw_center:+$('js_c').value,raw_full_pos:+$('js_fp').value,raw_full_neg:+$('js_fn').value,raw_deadband:+$('js_db').value,vel_accel_up:+$('js_aup').value,vel_accel_dn:+$('js_adn').value,vel_accel_jerk:+$('js_ajk').value}});\n"
    "    toast('joystick applied');loadConfig();\n"
    "  }catch(e){toast('apply failed: '+e,true);}\n"
    "}\n"
    "async function applyLoadFactor(v){\n"
    "  try{await post('/api/config',{dynamics:{load_factor:+v}});\n"
    "    toast('load factor '+(+v).toFixed(2)+' sent to motor');\n"
    "  }catch(e){toast('apply failed: '+e,true);}\n"
    "}\n"
    "// Slider: live update of the displayed value during drag (input event);\n"
    "// only POST to /api/config on release (change event). Matches operator\n"
    "// expectation that the motor isn't being re-tuned 50 times per second\n"
    "// while they slide.\n"
    "(function bindLoadFactorSlider(){\n"
    "  const s = $('dyn_lf'); if (!s) return;\n"
    "  s.addEventListener('input',  e => { $('dyn_lf_val').textContent = (+e.target.value).toFixed(2); });\n"
    "  s.addEventListener('change', e => applyLoadFactor(e.target.value));\n"
    "})();\n"
    "async function saveAll(){\n"
    "  try{await post('/api/save');toast('saved to flash');}catch(e){toast('save failed: '+e,true);}\n"
    "}\n"
    "async function saveAndReboot(){\n"
    "  try{await post('/api/save');toast('saved; rebooting');await post('/api/reboot');}\n"
    "  catch(e){toast('save+reboot failed: '+e,true);}\n"
    "}\n"
    "loadConfig();\n"
    "setInterval(()=>{fetch('/api/config').then(r=>r.json()).then(c=>{$('js_cur').textContent=c.joystick.raw_current;$('st_up').textContent=c.status.uptime_pretty;const p=c.limits.position_current;$('pos_cur').textContent=(p==null)?'-':Number(p).toFixed(4);updateHoming(c.axis);}).catch(()=>{});},1000);\n"
    "</script>\n"
    "</body></html>\n";

const size_t WEB_INDEX_HTML_LEN = sizeof(WEB_INDEX_HTML) - 1u;  /* drop the trailing NUL */
